### ISSUE TITLE
麻烦问下作者是否愿意合并一个新版本

### ISSUE THREAD

**Issue by pzx521521** [jqorz/biquge_crack#2]
是这样的:
你提供的两个加固/未加固的版本是国内的
服务器API->*.1122dh.com(117.91.192.41 江苏省扬州市 电信)
还有一个google app的版本, 更容易去除广告, 因为要上架吧, 很多广告都是没有的,并且用的是这个服务器:
shuapi.jiaston.com(104.16.130.241 美国)
经测试, 所有接口一样, 包括后台数据库(用户名密码进度)也是一样的
并且搜索的接口
https://sou.jiaston.com/search.aspx?key=test&page=1&siteid=app2是可以使用并且没有改变的
猜测是用nginx转了一下, 分布式的概率较小(.Net分布式还是很难搞的)
如果你愿意的话, 我会fork后 Pull reqiests, 然后你合并下,

**Comment by jqorz** [comment]
GooglePlay版本是哪一个呢？是加固的还是未加固的呢？由于国内版的最新版使用了加固，没法处理所以我只能选择去掉了4.5版本的广告。如果你成功去除了最新版本的广告，很乐意进行合并。

**Comment by jqorz** [comment]
> 是这样的:
> 你提供的两个加固/未加固的版本是国内的
> 服务器API->*.1122dh.com(117.91.192.41 江苏省扬州市 电信)
> 还有一个google app的版本, 更容易去除广告, 因为要上架吧, 很多广告都是没有的,并且用的是这个服务器:
> shuapi.jiaston.com(104.16.130.241 美国)
> 经测试, 所有接口一样, 包括后台数据库(用户名密码进度)也是一样的
> 并且搜索的接口
> [https://sou.jiaston.com/search.aspx?key=test&page=1&siteid=app2是可以使用并且没有改变的](https://sou.jiaston.com/search.aspx?key=test&page=1&siteid=app2%E6%98%AF%E5%8F%AF%E4%BB%A5%E4%BD%BF%E7%94%A8%E5%B9%B6%E4%B8%94%E6%B2%A1%E6%9C%89%E6%94%B9%E5%8F%98%E7%9A%84)
> 猜测是用nginx转了一下, 分布式的概率较小(.Net分布式还是很难搞的)
> 如果你愿意的话, 我会fork后 Pull reqiests, 然后你合并下,

GooglePlay版本是哪一个呢？是加固的还是未加固的呢？由于国内版的最新版使用了加固，没法处理所以我只能选择去掉了4.5版本的广告。如果你成功去除了最新版本的广告，很乐意进行合并。

**Comment by pzx521521** [comment]
https://play.google.com/store/apps/details?id=com.googlebiquge.ebook.app
google play 中并没有所谓的6/7 版本 只有5这个版本
我Pull&nbsp;了 你看下要不要合
&nbsp;
------------------
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;祝生活愉快！
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;彭子旭（18868826592）


&nbsp;

**Comment by oldskooler** [comment]
下载了这里的谷歌版，启动速度太慢，打开后要等个10来秒

**Comment by jqorz** [comment]
谷歌版是别人合并提交的代码，不好定位问题原因。你用3.0的破解版吧------------------ 原始邮件 ------------------
发件人: "oldskooler"<notifications@github.com>
发送时间: 2019年10月21日(星期一) 上午10:49
收件人: "jqorz/biquge_crack"<biquge_crack@noreply.github.com>;
抄送: "jqorz"<j1997321@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [jqorz/biquge_crack] 麻烦问下作者是否愿意合并一个新版本 (#2)



下载了这里的谷歌版，启动速度太慢，打开后要等个10来秒
 
&mdash;
