### ISSUE TITLE
额 那个破解版的安装包为什么那么大

### ISSUE THREAD

**Issue by clks01** [jqorz/biquge_crack#4]
额 那个破解版的安装包为什么那么大

**Comment by jqorz** [comment]
用3.0的那个版本就OK了------------------ 原始邮件 ------------------
发件人: "clks01"<notifications@github.com>
发送时间: 2019年11月2日(星期六) 下午5:19
收件人: "jqorz/biquge_crack"<biquge_crack@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [jqorz/biquge_crack] 额 那个破解版的安装包为什么那么大 (#4)



额 那个破解版的安装包为什么那么大
 
&mdash;

**Comment by clks01** [comment]
谢谢 这是我人生中第一个 lssues 而且您回复那么迅速 很高兴 3.0的安装包地址是多少

**Comment by clks01** [comment]
谢谢 我找到了 好蠢啊
